# TODO: Update this to use the release from CFN once merged
repos:
-   repo: https://github.com/dannyvassallo/cloudformation-guard
    rev: pre-commit-v0.0.76
    hooks:
        -   id: cfn-guard
            args:
                - "--rules=./guard/resources/validate/rules-dir/"