# TODO: Update this to use the release from CFN once merged
repos:
-   repo: https://github.com/dannyvassallo/cloudformation-guard
    rev: pre-commit-v0.0.63
    hooks:
        -   id: cfn-guard
            args: [--max-line-length=131]
