# TODO: Update this to use the release from CFN once merged
repos:
-   repo: https://github.com/dannyvassallo/cloudformation-guard
    rev: pre-commit-v0.0.84
    hooks:
        -   id: cfn-guard
            args:
                - validate
                - "--rules=guard/resources/validate/rules-dir/"
            files: ^guard/resources/validate/data-dir/.*
        -   id: cfn-guard
            args:
                - test
                - "--rules=guard/resources/test-command/rule-dir/"
            files: ^guard/resources/test-command/data-dir/.*