name: 'CFN Guard GitHub Action'
description: 'Validate templates using CFN Guard'
author: 'Amazon Web Services'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  rules:
    description: 'rules path'
    required: true
    default: '.'
  data:
    description: 'data path'
    required: true
    default: '.'

# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: ./action/dist/index.js
