name: 'Guard Validate'
description: 'Validate templates using cfn-guard'
inputs:
  rules:
    description: 'Rules file or directory'
    required: true
  data:
    description: 'Data file or directory'
    required: true
runs:
  using: 'docker'
  image: './action/Dockerfile'
  args:
    - ${{ inputs.rules }}
    - ${{ inputs.data }}
