name: CFN Guard Test

on: [pull_request]

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    name: Guard Test
    steps:
      - name: CFN Guard Test
        uses: dannyvassallo/cloudformation-guard/actions/test@v1.47
        with:
          tests: './test-resources/api_gateway_private_access_tests.yaml'
          rules: './test-resources/api_gateway_private_access.guard'
