name: CFN Guard Validate

on: [pull_request]

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    name: Guard
    steps:
      - name: CFN Guard Validate
        uses: dannyvassallo/cloudformation-guard/actions/validate@v1.46
        with:
          rules: './guard/resources/validate/rules-dir/'
          data: './guard/resources/validate/data-dir/'
