on: [pull_request, push]

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      checks: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    name: Guard
    steps:
      - name: CFN Guard Action
        uses: dannyvassallo/cloudformation-guard@v1.44
        with:
          rules: './guard/resources/validate/rules-dir/'
          data: './guard/resources/validate/data-dir/'
