name: Pre-Commit Hook CI
on:
  push:
    paths:
      - 'pre_commit_hooks/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'pre_commit_hooks/**'
      - 'tests/**'
jobs:
  run-unit-tests-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests & linters
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install -r requirements-dev.txt
      - run: find . -iname '*.py' | xargs pylint
      - run: pytest ./tests/
      - run: black --check .
  integ-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: sudo snap install pre-commit --classic
      - run: pre-commit install
      - run: pre-commit run
