name: Pre-Commit Hook CI
on:
  push:
    paths:
      - 'pre_commit_hooks/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'pre_commit_hooks/**'
      - 'tests/**'
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests & linters
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install -r requirements-dev.txt
      - run: pylint --disable=bare-except,invalid-name --class-rgx='[A-Z][a-z]+' --generate-rcfile
      - run: pytest ./tests/
      - run: black --check .
