name: CFN Guard Validate

on: [pull_request]

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
    name: Guard Validate
    steps:
      - name: CFN Guard Validate
        uses: dannyvassallo/cloudformation-guard@action-v0.0.0
        with:
          rules: './guard/resources/validate/rules-dir/'
          data: './guard/resources/validate/data-dir/'
